image: registry.gitlab.com/gitlab-org/terraform-images/branches/v1-6-0-1.3:f158d31c1356d14029d8285ddd4b79ebbe6d7e90

variables:
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/default

cache:
  paths:
    - .terraform

before_script:
  - gitlab-terraform init -upgrade

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - gitlab-terraform validate

plan:
  stage: plan
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - plan.cache
    reports:
      terraform: plan.json

apply:
  stage: apply
  allow_failure: false
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  only:
    - master
    - main

destroy:
  stage: destroy
  allow_failure: false
  script:
    - gitlab-terraform destroy -auto-approve
  when: manual
  only:
    - master
    - main
